# -*- coding: utf-8 -*-
"""matplotlib.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13KwI70a-XkiV44oj6rgfHSmEJ9U9qZtH
"""

import matplotlib.pyplot as plt
import numpy as np
x=np.array([0,1,2,3,4,5])
y=np.array([0,2,8,1,14,7])
plt.scatter(x,y, color='green')
plt.show()

x=np.array([0,1,2,3,4,5])
y=np.array([0,2,8,1,14,7])
mycolor=['red','green','purple','lime','aqua','yellow']
size=[10,60,120,80,20,190]
plt.scatter(x,y,color=mycolor,s=size)
plt.show()

x=np.array(['A','B','C','D'])
y=np.array([3,8,1,10])
plt.bar(x,y)
plt.show()

x=np.array(['A','B','C','D'])
y=np.array([3,8,1,10])
plt.barh(x,y)
plt.show()

x=np.array(['A','B','C','D'])
y=np.array([3,8,1,10])
plt.bar(x,y,width=0.1)
plt.show()

x=np.array([35,25,25,15])
plt.pie(y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([35,25,25,15])
mylables=["Apples","Bananas","Cherries","Dates"]
plt.pie(x,labels=mylables)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([35,25,25,15])
mylables=["Apples","Bananas","Cherries","Dates"]
plt.pie(x,labels=mylables,startangle=90)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([35,25,25,15])
mylables=["Apples","Bananas","Cherries","Dates"]
myexplode=[0.2,0,0,0]
plt.pie(x,labels=mylables,startangle=90,explode=myexplode)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([35,25,25,15])
mylables=["Apples","Bananas","Cherries","Dates"]
myexplode=[0.2,0,0,0]
plt.pie(x,labels=mylables,startangle=90,explode=myexplode,shadow=True)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([35,25,25,15])
mylables=["Apples","Bananas","Cherries","Dates"]
mycolors=["black",'hotpink','b','#4CAF50']
myexplode=[0.2,0,0,0]
plt.pie(x,labels=mylables,startangle=90,explode=myexplode,colors=mycolors)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([35,25,25,15])
mylables=["Apples","Bananas","Cherries","Dates"]


plt.pie(x,labels=mylables)
plt.legend()
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([35,25,25,15])
mylables=["Apples","Bananas","Cherries","Dates"]


plt.pie(x,labels=mylables)
plt.legend(title='Four Fruits:')
plt.show()